# Generated by Django 5.2.13 on 2026-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixes', '0009_mix_share_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
