# Generated by Django 5.2.13 on 2026-06-05 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixes', '0010_alter_mix_processing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('total_size', models.PositiveBigIntegerField()),
                ('chunk_size', models.PositiveIntegerField()),
                ('total_chunks', models.PositiveIntegerField()),
                ('received_chunks', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cover_temp_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='uploading', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status', '-created_at'], name='upload_session_owner_idx'), models.Index(fields=['status', 'created_at'], name='upload_session_cleanup_idx')],
            },
        ),
    ]
